name: PR CI

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get install -y build-essential python-dev-is-python3 python3-numpy python3-pytest cppcheck

    - name: Build library
      run: make c PYTHON=python

    - name: Run library tests
      run: make test PYTHON=python

    - name: Copy library to docs/ directory
      run: cp -r permanent/ docs/permanent/

    - name: Build documentation
      uses: ammaraskar/sphinx-action@master
      with:
        build-command: "make html"
        docs-folder: "docs/"

    - name: Fix documentation permissions
      run: |
        chmod -c -R +rX "docs/build/html/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
        done

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/build/html/

  cppcheck:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run cppcheck
        run: cppcheck --enable=all --suppress=missingIncludeSystem -I src/ .

      - name: Publish cppcheck report
        uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'main'
