name: Pull Request Docs Check

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: sudo apt-get install -y build-essential python-dev-is-python3 python3-numpy

    - name: Build library
      run: make PYTHON=python && cp -r permanent/ docs/

    - uses: ammaraskar/sphinx-action@master
      with:
        build-command: "make html"
        docs-folder: "docs/"

    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/build/html/
